resources-template: &resources-template
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

controller:
  <<: *resources-template
  autoscaling:
    ## Create the HorizontalPodAutoscaler resource.  This can be set to false to manage the HPA externally.
    create: false
  
  initContainerResources:
    <<: *resources-template

prometheus:
  ## Expose NGINX or NGINX Plus metrics in the Prometheus format.
  create: false
